# **Linear Algebra**

### **1. $\vec{c} \cdot \vec{d}$ 값 구해보기**

\begin{align}
\vec{c} = \begin{bmatrix}3 & 7 & -2 & 12\end{bmatrix}
\qquad
\vec{d} = \begin{bmatrix}9 & -7 & 4 & 6\end{bmatrix}
\end{align}

In [ ]:
import numpy as np
import pandas as pd 

c=np.array([3,7,-2,12]).T
d=np.array([9,-7,4,6])

print('cT와 d의 내적 값이 ',np.dot(c,d),'이므로 0이 아니다. 따라서 직교하지 않다.')


cT와 d의 내적 값이  42 이므로 0이 아니다. 따라서 직교하지 않다.


### **2. $E^{-1}$ 와 $E^{T}$ 산출**

\begin{align}
E = 
\begin{bmatrix}
    7 & 4 & 2 \\
    1 & 3 & -1 \\
    2 & 6 & -4
\end{bmatrix}
\end{align}

In [ ]:
E = np.array([[7,4,2],[1,3,-1],[2,6,-4]])

print('역행렬 :\n',np.linalg.inv(E),'\n')
print('전치행렬 :\n',E.T)

역행렬 :
 [[ 0.17647059 -0.82352941  0.29411765]
 [-0.05882353  0.94117647 -0.26470588]
 [ 0.          1.         -0.5       ]] 

전치행렬 :
 [[ 7  1  2]
 [ 4  3  6]
 [ 2 -1 -4]]


### **3. $|F|$ 산출**

\begin{align}
F = 
\begin{bmatrix}
    2 & -2 & 5 \\
    4 & 1 & 10 \\
    12 & 6 & 30
\end{bmatrix}
\end{align}

In [ ]:
F = np.array([[2,-2,5],[4,1,10],[12,6,30]])

np.linalg.det(F)
print('det 값이 0이므로 역행렬이 존재하지 않는다.')

det 값이 0이므로 역행렬이 존재하지 않는다.


### **4. 다음 데이터의 covariance, correlation 구하기**

- x = [820, 760, 1250, 990, 1080, 1450, 1600]

- y = [0, 1, 7, 1, 0, 6, 4]

In [ ]:
x = [820, 760, 1250, 990, 1080, 1450, 1600]
y = [0, 1, 7, 1, 0, 6, 4]

df = pd.DataFrame({'x':x,'y':y})

# covariance 산출
df.cov()

x           y
x  98761.904762  670.238095
y    670.238095    8.571429

In [ ]:
# correlation 산출
df.corr()

x         y
x  1.000000  0.728463
y  0.728463  1.000000

### **5. 정규화**


In [ ]:
import pandas as pd

# 임의의 데이터셋 생성 - 정규화 실습 위함
data = {"Country": ["England","Wales","Scotland","North Ireland"], 
        "Cheese": [105,103,103,66], 
        "Carcass_Meat": [245,227,242,267], 
        "Other_Meat": [685, 803, 750, 586], 
        "Fish": [147, 160, 122, 93], 
        "Fats_and_Oils": [193, 235, 184, 209], 
        "Sugars": [156, 175, 147, 139], 
        "Fresh_Potatoes": [720, 874, 566, 1033], 
        "Fresh_Veg": [253, 265, 171, 143], 
        "Other_Veg": [488, 570, 418, 355], 
        "Processed_Potatoes": [198, 203, 220, 187], 
        "Processed_Veg": [360, 365, 337, 334], 
        "Fresh_Fruit": [1102, 1137, 957, 674], 
        "Cereals": [1472, 1582, 1462, 1494], 
        "Beverages": [57,73,53,47], 
        "Soft_Drinks": [1374, 1256, 1572, 1506], 
        "Alcoholic Drinks": [375, 475, 458, 135], 
        "Confectionery": [54, 64, 62, 41]}

df = pd.DataFrame(data)
df

Country  Cheese  ...  Alcoholic Drinks  Confectionery
0        England     105  ...               375             54
1          Wales     103  ...               475             64
2       Scotland     103  ...               458             62
3  North Ireland      66  ...               135             41

[4 rows x 18 columns]

In [ ]:
# 정규화 실행
df.set_index(keys='Country',inplace=True)
np.multiply((1/np.linalg.norm(df, ord=None, axis=None, keepdims=False)),df)

Cheese  Carcass_Meat  ...  Alcoholic Drinks  Confectionery
Country                                ...                                 
England        0.019584      0.045697  ...          0.069944       0.010072
Wales          0.019211      0.042339  ...          0.088596       0.011937
Scotland       0.019211      0.045137  ...          0.085425       0.011564
North Ireland  0.012310      0.049800  ...          0.025180       0.007647

[4 rows x 17 columns]